name: Publish Package to npmjs
on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - name: Build and test
        run: npm run build && npm test
      - if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
